language: ruby
sudo: false

before_install:
  - gem install -v 1.17.3 bundler
  - bundle _1.17.3_ install

rvm:
  - 2.5.7
  - 2.6.5

gemfile:
  - test/gemfiles/Gemfile.rails-4.x
  - test/gemfiles/Gemfile.rails-5.x
  - test/gemfiles/Gemfile.rails-6.x
  - test/gemfiles/Gemfile.rails-edge
